

# models/config/gan_config.yaml

train_pairs_path: /kaggle/input/image-restoration-dataset/data/splits/train_pairs.txt
val_pairs_path: /kaggle/input/image-restoration-dataset/data/splits/val_pairs.txt
raw_image_root: /kaggle/input/image-restoration-dataset/data/raw
corrupted_image_root: /kaggle/input/image-restoration-dataset/data/corrupted
checkpoint_dir: /kaggle/working
results_dir: /kaggle/working

# Model parameters
image_size:  [256,256]  

# Training parameters
batch_size: 4           
epochs: 100
learning_rate_g: 0.0001
learning_rate_d: 0.0004 
beta1: 0.5              
lambda_L1: 100
